name: Test

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches: 
      - "main"
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v7.0.0

    - uses: actions/setup-go@v6.4.0
      with:
        go-version-file: go.mod
        cache: true

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.14.0

    - name: Go Generate
      run: go generate ./...

    - name: Go install
      run: go install .

    - name: Run cache-kube-schemas
      run: yes | yisp cache-kube-schemas

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./...

