name: Test

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches: 
      - "main"
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.2'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Go Generate
      run: go generate ./...

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./pkg/...

